### ISSUE TITLE
Issuehunt or similar to fund development?

### ISSUE THREAD

**Issue by bobzoller** [rudderlabs/rudder-transformer#101]
Features requests (like #100) have real value to our business. I'd love to see some way for folks to fund Rudderstack community development, ala https://issuehunt.io/ or similar.

Has this already been discussed?

**Comment by SumanthPuram** [comment]
We did not come across issuehunt before. Tha ks for the pointer @bobzoller. This definitely sounds like a great option for us. We have been exploring how to encourage community development.

We will look into Issuehunt. Do you suggest any other options?

**Comment by bobzoller** [comment]
I've never used it either to be honest, I just knew the concept existed.

**Comment by SumanthPuram** [comment]
Done! Integrated issuehunt with our repo, seems like a good option.
