### ISSUE TITLE
GA Campaign ID missing

### ISSUE THREAD

**Issue by juronja** [rudderlabs/rudder-transformer#1050]
Hey guys.

There are a few important google analytics properties missing especially:

sr - https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#sr
vp - https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#vp
ci - https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ci
gclid - https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#gclid
dclid - https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#dclid

We already collect resolution info, but the transformer is not forwarding this info to the destination.
Campaign ID and Google Ads ID are also very important when working with ad platforms.

Can please somebody include this in the transformer for GA?

**Comment by akashrpo** [comment]
This issue has been addressed in PR #1077. Hence closing it.
