### ISSUE TITLE
Facebook Pixel Support

### ISSUE THREAD

**Issue by arnabp92** [rudderlabs/rudder-transformer#111]
Relevant Pages:

- https://developers.facebook.com/docs/facebook-pixel/

**Comment by Sshuichi** [comment]
If we could have cloud mode for this, it would be awesome!

**Comment by pawanakhil** [comment]
I think Mautic Open Source tool does this work easily. It also available in AWS Marketplace and Google Cloud Deploy. 

Ref: 
[1] https://docs.mautic.org/en/contacts/manage-contacts/contact-monitoring
[2] https://developer.mautic.org/#introduction

**Comment by ruchiramoitra** [comment]
@Sshuichi we have released it.

**Comment by Sshuichi** [comment]
@ruchiramoitra can you please guide me to the documentation?
