### ISSUE TITLE
Mixpanel where users were merged when sharing devices

### ISSUE THREAD

**Issue by nauxliu** [rudderlabs/rudder-transformer#1180]
When two users share one device, these two users will be merged, and it's irreversible. this is a really serious issue for us.

Suppose a scenario like this.
1. The first time a user visits, an anonymous ID is generated: A
2. User B logged in and the anonymous ID A and user id B were merged
3. User C logged in with the same device, anonymous ID A and user C were merged
4. Causes two separate users B and C to be merged on Mixpanel

Mixpanel has a mechanism to prevent issues like this if the anonymous ID is in UUID v4 format when calling identity
https://developer.mixpanel.com/reference/create-identity
![image](https://user-images.githubusercontent.com/9570112/167987952-6c01876a-510c-446d-bb2a-8627ee6e8a7d.png)

Looks like we are calling `$merge` directly instead of using the `$identity`, probably because the user id was not in UUID v4 format at the time?
https://github.com/rudderlabs/rudder-transformer/blob/master/v0/destinations/mp/transform.js#L236-L282

Since [we are generating anonymous ID in UUID v4 now](https://github.com/rudderlabs/rudder-sdk-js/blob/b78174bf795083d43ff189ac3ae45b278168e024/utils/utils.js#L37-L51), we should uncomment the code to use `$identity` to merge anonymous id and user id. to take advantage of the Mixpanle merge mechanism to prevent users get merged.

**Comment by devops-github-rudderstack** [comment]
This issue is considered to be stale. It has been open for 30 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the issue.
