### ISSUE TITLE
GetVero Support

### ISSUE THREAD

**Issue by bricemaurin** [rudderlabs/rudder-transformer#1227]
Hi,
we're planning on moving from segment to rudderstack, but you don't seem to support the Vero integration yet..so it's blocking us from moving :'(

Ideally, i'd love to get the same level of integration that the one you propose on customerio:
- push identify calls
- push track calls

here's the vero documentation: https://developers.getvero.com/

thanks !

**Comment by utsabc** [comment]
@bricemaurin thanks for the query we will definitely check this and put in our dev pipeline

**Comment by JauneJaune** [comment]
Up ! need the same !
