### ISSUE TITLE
Feature suggestion: NATS JetStream Destination

### ISSUE THREAD

**Issue by gedw99** [rudderlabs/rudder-transformer#1229]
Would be useful for me and maybe others to have a NATS Jetstream Destination.

https://github.com/nats-io/nats.go

**Comment by devops-github-rudderstack** [comment]
This issue is considered to be stale. It has been open for 30 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the issue.

**Comment by jobcespedes** [comment]
Please reconsider
