### ISSUE TITLE
Elasticsearch connector

### ISSUE THREAD

**Issue by benedikt-buchert** [rudderlabs/rudder-transformer#1230]
Adding an elasticsearch connector could be a very interesting option. 

Would open a whole universe of possibilities. 

- Kibana Dashboards
- Real-time searching
and many more.

**Comment by devops-github-rudderstack** [comment]
This issue is considered to be stale. It has been open for 30 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the issue.
