### ISSUE TITLE
Amplitude doesn't work with integer user ids

### ISSUE THREAD

**Issue by vicampuzano** [rudderlabs/rudder-transformer#127]
Hi Guys! ;) 

Congraturations! RudderStack it's becoming "my new passion" ;) You're doing a great job 👏🏻

I'm sharing with you a small issue I detected when using integer user_id and trying to send events to Amplitude.

It causes an error 400: "events_with_invalid_user_id_length"

It's because Amplitude's default minimum user_id length is 5. Using integer values, all users ids between 1 and 9999 will cause the error.

By attaching min_id_length property to the Amplitude's call, you can set the minimum length to 1 and allow all integer values. 

This option must be passed outside the events collections in the JSON structure. It's at the user_id level.

You can see more info here: help.amplitude.com/hc/en-us/articles/360032842391-HTTP-API-V2#device-ids-and-user-ids-minimum-length

Here you are a tested and working call:
```
{
    "api_key": "{{api_key}}",
    "options": {
    	"min_id_length": 1
    },
    "events": [
        {
            "user_id": "123",
            "event_type": "completeRegistration",
            "time": 1583909415,
            "event_properties": {
            	........
            },
            "user_properties": {
            	
            }
        }
    ]
}
```

I hope you find this useful...

Thanks!

**Comment by arnabp92** [comment]
Fixed in #128

**Comment by vicampuzano** [comment]
🙌

**Comment by navff** [comment]
This is not fixed in python SDK: https://www.docs.developers.amplitude.com/data/sdks/python/
There is no event when i send "99", but it works with USER_99. Can you fix it?
