### ISSUE TITLE
TikTok Not getting IP

### ISSUE THREAD

**Issue by jjhuff** [rudderlabs/rudder-transformer#1274]
In order to get TikTok to work, I had to do 
`event.context.ip = event.request_ip`
in a transformer.

I'm a little confused since the Rudderstack docs imply that `context.ip` should be populated automatically.

**Comment by utsabc** [comment]
By default we capture the `ip` in `event.request_ip` if the user want's to override or anonymize the `ip` it can be set at `event.context.ip`
[Reference](https://www.rudderstack.com/docs/event-spec/standard-events/common-fields/)
![Screenshot 2022-08-18 at 9 01 44 AM](https://user-images.githubusercontent.com/25389167/185287123-58734b13-df8c-4901-a732-0e7859281389.png)

**Comment by jjhuff** [comment]
@utsabc the problem is that the TikTok destination wasn't reading the IP from event request_ip -- only from event.context.ip. 
That means the integration is non-functional without the transformer mentioned above.

Other destinations use event.context.ip if it's set, otherwise, they use event.request_ip.

**Comment by utsabc** [comment]
Got it, checking it will raise the fix and tag it here

**Comment by jjhuff** [comment]
@utsabc thanks!!

**Comment by utsabc** [comment]
Fix [PR](https://github.com/rudderlabs/rudder-transformer/pull/1355)
