### ISSUE TITLE
Customer.io transformer throws an error in group call.

### ISSUE THREAD

**Issue by mderazon** [rudderlabs/rudder-transformer#1290]
Customer.io transformer throws an error in group call.

https://github.com/rudderlabs/rudder-transformer/blob/7f77333f491956e3137159dcd44813daa3ada1fd/v0/destinations/customerio/transform.js#L286

I have two transformers running - MP and CIO. CIO throws an error because it doesn't support `group` but MP supports group and should still be getting the group call, however it looks like it is failing due to error in CIO transformer

**Comment by mderazon** [comment]
@mihir-4116 is this supposed to be solved with https://github.com/rudderlabs/rudder-transformer/pull/1869 ?

Can you explain the approach ? As CIO doesn't have inherint group calls afaik

**Comment by mihir-4116** [comment]
Yes, we have released group call support for customerio, plz refer docs how to implement them

**Comment by mderazon** [comment]
@mihir-4116 on the customer.io side does it map to Objects ?
https://customer.io/docs/objects/
?

The Rudderstack doc doesn't mention that
