### ISSUE TITLE
Parsing user agent data for posthog properties

### ISSUE THREAD

**Issue by juronja** [rudderlabs/rudder-transformer#1296]
I think it would be a usefull feature if parsing the context.userAgent would be enabled natively in rudderstack.
Similar to the community plugin solution for Posthog: 
https://github.com/weyert/useragentplugin

**Comment by devops-github-rudderstack** [comment]
This issue is considered to be stale. It has been open for 30 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the issue.
