### ISSUE TITLE
AppsFlyer unit tests are disabled

### ISSUE THREAD

**Issue by orrc** [rudderlabs/rudder-transformer#1308]
I was making a small fix to the AppsFlyer source, and so updated the test data, and wanted to run the unit tests…

However, it looks like the unit tests were [entirely commented out](https://github.com/rudderlabs/rudder-transformer/commit/ed031482f79d510609ee7e5b113b38154ca3c3a0), as part of #1033.

It seems some sort of change needs to be made, as the unit tests, if uncommented, currently fail to run:
> `Cannot find module 'rudder-transformer-cdk' from '__tests__/utilities/test-utils.js'`

**Comment by sanpj2292** [comment]
Hi @orrc ,

Thank you for trying to contribute to Rudderstack code-base.
Can you let me know if you've deleted the `node_modules` and did an `npm install` after making changes to appsFlyer source ?

Wanted to share that the testing code is present but it is present as part of a utility function and the older way of writing tests has been commented out

Kindly reply back for the question, we'll get back to you as soon as we can!

Thank you

**Comment by orrc** [comment]
Hey, thanks for the quick reply!

I took a deeper look, and I think overall things are fine:
- Doing a clean `npm install`, and running the commented-out code in `__tests__/appsFlyer.test.js`, there were no more runtime errors — only test failures.
- But as you mention, that commented-out code is old — the remaining code at the bottom of the file executes the processor/router tests without any problems, and all they all pass.
- However, in order to test the AppsFlyer source (which is what I want to do), I should actually be executing a _different_ unit test file: `__tests__/appsflyer_source.test.js` (which also works fine).

So I guess perhaps just a small code cleanup would be good here, but otherwise feel free to close this :)

**Comment by sanpj2292** [comment]
Thanks @orrc . Happy to see that you were able to make things work.
Will be closing this issue. Let us know if anything else comes up.
