### ISSUE TITLE
Attribution issues in AppsFlyer

### ISSUE THREAD

**Issue by kishorekumarsingh** [rudderlabs/rudder-transformer#1451]
Due to recent code changes (https://github.com/rudderlabs/rudder-transformer/pull/1390),  AppsFlyer is recording our events as new events. 
Earlier, `EventName` transformed to `eventname`. But now, it stays as `EventName`. According to AppsFlyer

Also, there is some issue with eventValue format. [AppsFlyer docs](https://support.appsflyer.com/hc/en-us/articles/207034486#eventvalue-7) mention that this should be the format of the eventValue,
```
"eventValue": 
	"{
		\"af_revenue\": \"1006\",
		\"af_content_type\": \"wallets\",
		\"af_content_id\": \"15854\",
		\"af_quantity\" :\"1\"
   }"
```

**Comment by utsabc** [comment]
Hello @kishorekumarsingh we had to make this change in order to keep flexibility of choosing casing by customers not us. In order to mitigate this issue you can use `userTransformation` to transform your event names to lower case before sending tot Appsflyer. 
We would be happy yo help you on that regard.

Regarding the second issue. Can you please clarify what is the exact issue here?

**Comment by kishorekumarsingh** [comment]
Sure, So appsflyer expects eventValue to be of this format 
```
"eventValue": 
	"{
		\"af_revenue\": \"1006\",
		\"af_content_type\": \"wallets\",
		\"af_content_id\": \"15854\",
		\"af_quantity\" :\"1\"
   }"
```

But I can see in the control plane that Rudder is trying to send,
```
"eventValue": 
"{\"properties\":
	"{
		\"af_revenue\": \"1006\",
		\"af_content_type\": \"wallets\",
		\"af_content_id\": \"15854\",
		\"af_quantity\" :\"1\"
   }"
}"
```

**Comment by utsabc** [comment]
Got it looking into it

**Comment by yashasvibajpai** [comment]
@kishorekumarsingh Can you please provide some of your event payloads for us to verify on our end?

**Comment by kishorekumarsingh** [comment]
Hi @yashasvibajpai , Sure

```
[
    {
        "eventName": "TestEvent",
        "eventType": "track",
        "payload": {
            "anonymousId": "dkhjgdkjwiufnjskwhkr",
            "context": {
                "externalId": [
                    {
                        "id": "99999999-23432432",
                        "type": "appsflyerExternalId"
                    }
                ],
                "os": {
                    "name": "android",
                    "version": "8.1.0"
                }
            },
            "event": "TestEvent",
            "messageId": "e9b620fe-9a77-4f51-8dd2-121562cf42c0",
            "originalTimestamp": "2022-09-29T03:49:01.299Z",
            "properties": {
                "Currency": "INR",
                "FailureReason": "",
                "InsertId": "",
                "IsFirstAttempt": false,
                "Mode": "UPI",
                "ProcessingTime": 18,
                "SignupTag": "D753",
                "TransactionId": "",
                "advertisement_id": "",
                "af_currency": "INR",
                "af_events_api": true,
                "af_revenue": "50",
                "android_id": "",
                "app_version": "",
                "app_version_code": 0,
                "appsFlyerId": "9999999999-09999999999",
                "currency": "INR",
                "customer_user_id": "jkscnskdqsclsdfvff",
                "deposit_amount": 50,
                "eventCurrency": "INR",
                "event_uid": "a34bbd32-6081-4fef-859b-d080bfb8202f-8841",
                "instance_id": 0,
                "ip_address": "",
                "offer_applied": false,
                "offer_id": "",
                "offer_type": "Default",
                "payment_aggregator": "Juspay",
                "payment_gateway": "GOCASHFREE",
                "payment_instrument": "Phonepe",
                "payment_status": "Complete",
                "platform": "",
                "serial_number": "",
                "status": "Complete",
                "sub_mode": "INTENT",
                "user_id": "kgtnwkjnvwlrinwv",
                "vendor_id": "",
                "widevine_id": ""
            },
            "receivedAt": "2022-09-29T03:49:01.142Z",
            "request_ip": "10.16.1.8",
            "rudderId": "20b135ee-a76c-44f6-bf0c-e9277afeba5a",
            "sentAt": "2022-09-29T03:49:01.299Z",
            "timestamp": "2022-09-29T03:48:59.155Z",
            "type": "track",
            "userId": "kgtnwkjnvwlrinwv"
        }
    }
]
```

**Comment by yashasvibajpai** [comment]
Thank you for your response @kishorekumarsingh. We investigated over this and seemingly with the above payload, we are getting a stringified object and some other attributes in the `eventValue`. It is present as shown here :-
`"{\"properties\":{\"Currency\":\"INR\",\"FailureReason\":\"\",\"InsertId\":\"\",\"IsFirstAttempt\":false,\"Mode\":\"UPI\",\"ProcessingTime\":18,\"SignupTag\":\"D753\",\"TransactionId\":\"\",\"advertisement_id\":\"\",\"af_currency\":\"INR\",\"af_events_api\":true,\"af_revenue\":\"50\",\"android_id\":\"\",\"app_version\":\"\",\"app_version_code\":0,\"appsFlyerId\":\"9999999999-09999999999\",\"currency\":\"INR\",\"customer_user_id\":\"jkscnskdqsclsdfvff\",\"deposit_amount\":50,\"eventCurrency\":\"INR\",\"event_uid\":\"a34bbd32-6081-4fef-859b-d080bfb8202f-8841\",\"instance_id\":0,\"ip_address\":\"\",\"offer_applied\":false,\"offer_id\":\"\",\"offer_type\":\"Default\",\"payment_aggregator\":\"Juspay\",\"payment_gateway\":\"GOCASHFREE\",\"payment_instrument\":\"Phonepe\",\"payment_status\":\"Complete\",\"platform\":\"\",\"serial_number\":\"\",\"status\":\"Complete\",\"sub_mode\":\"INTENT\",\"user_id\":\"kgtnwkjnvwlrinwv\",\"vendor_id\":\"\",\"widevine_id\":\"\"},\"af_currency\":\"INR\"}`

We wanted to confirm how is this nested object inside `eventValue` being treated on Appsflyer's end. Can you do a raw export of your report and share it with us? It will be better if we can connect over a call to discuss this over. Please let us know.

**Comment by kishorekumarsingh** [comment]
@yashasvibajpai sorry for the late response.
We can surely get on a call to discuss this.

**Comment by yashasvibajpai** [comment]
@kishorekumarsingh can you please share your email? We can schedule a zoom meet

**Comment by kishorekumarsingh** [comment]
Sure, It's kumarsingh14.kishore@gmail.com

**Comment by devops-github-rudderstack** [comment]
This issue is considered to be stale. It has been open for 30 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the issue.
