### ISSUE TITLE
Custom Transformation Won't Work for Self-Hosted node

### ISSUE THREAD

**Issue by donald-stolz** [rudderlabs/rudder-transformer#157]
We are using a [custom transformation](https://github.com/donald-stolz/sample-user-transformers/blob/master/Clean_Empty_Stringify_Arrays_Camel_to_Snake_Case_UTM_Parameters.js) and our events do not make it to their destinations when we run our self-hosted node. If we use the demo node everything works as expected

VM Details:
- GCP Compute Engine
- Machine type: n1-highcpu-2 (2 vCPUs, 1.8 GB memory)
- Image debian-10-busterv20200521
- Size 10GB

**Comment by SumanthPuram** [comment]
One possible reason could be because of low resources. Can you try with a machine that has at least 8 GB?

**Comment by donald-stolz** [comment]
@SumanthPuram Hey, I switched the machine to one with 15 GB. Now everything is working as expected. Thank you for the help. It'd be great if you guys could add some minimum/recommended VM details somewhere in the README
