### ISSUE TITLE
Request: Addition of new destination "Taboola Pixel"

### ISSUE THREAD

**Issue by ManojLenka** [rudderlabs/rudder-transformer#1595]
It would be great if RudderStack support "Taboola Pixel" as destination. The Taboola Pixel is the engine that drives our campaign's success.

**Comment by devops-github-rudderstack** [comment]
This issue is considered to be stale. It has been open for 30 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the issue.
