### ISSUE TITLE
Pipedream integration

### ISSUE THREAD

**Issue by dylburger** [rudderlabs/rudder-transformer#1608]
Hi, I'm a founder and engineer at [Pipedream](https://pipedream.com/). We just developed [a Pipedream integration for Rudderstack](https://pipedream.com/apps/rudderstack/), and wanted to reach out to see if y'all could help develop an integration on your side for Pipedream, as well.

Pipedream functions a lot like [Zapier](https://zapier.com/). Users would create [an HTTP endpoint](https://pipedream.com/docs/workflows/steps/triggers/#http) in Pipedream and send data from Rudderstack. Pipedream will accept data in whatever format users want, since they control the HTTP endpoint.

It may also make sense to have Pipedream function as a source, since users are likely to send data from Pipedream to Rudderstack. We chatted with a couple of members of your team about that [here](https://github.com/PipedreamHQ/pipedream/issues/1972#issuecomment-1324925375).

**Comment by arnab-p** [comment]
@dylburger Thanks for building the integration for RudderStack. Appreciate it. 

From the RudderStack side, we are planning to build the Pipedream connectors both as a source and destination latest by the end of this quarter. CC @ItsSudip 

Also, adding @BadriV1 here. He is our PM for the Transformation feature. He will take the transformation integration further.

**Comment by dylburger** [comment]
Awesome, thanks @arnab-p ! Let us know if you need any support from our side.

**Comment by anantjain45823** [comment]
Closing this Issue as Pipedream as destination and source both is released

**Comment by dylburger** [comment]
That’s great! I’ll update our docs to reference yours, as well
