### ISSUE TITLE
[Bug] Issue in mapping events on FB pixel destination

### ISSUE THREAD

**Issue by Sshuichi** [rudderlabs/rudder-transformer#161]
We are trying to map events to FB events but whatever we put in the FB event dropdown and save, it's blank when we get back: 
![image](https://user-images.githubusercontent.com/5939429/83935163-f640e500-a7c7-11ea-9a9d-63640aa2c60b.png)

**Comment by arnabp92** [comment]
@Sshuichi , Will look into it ASAP.

**Comment by Sshuichi** [comment]
Any luck? @arnabp92

**Comment by arnabp92** [comment]
@Sshuichi, We've fixed the issue. We will move it to production today.

**Comment by Sshuichi** [comment]
What a good news!! Cc @tantawi

**Comment by arnabp92** [comment]
@Sshuichi We've fixed the issue
