### ISSUE TITLE
Add support for URLSearchParams

### ISSUE THREAD

**Issue by johnpkennedy** [rudderlabs/rudder-transformer#1714]
Support the URLSearchParams class to make it easier to work with URL query parameters in transformations.

**Reference**
* https://nodejs.org/api/url.html#class-urlsearchparams
* https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

**Comment by Jayachand** [comment]
Rudderstack does not support `URLSearchParams` in javascript transformations. Will keep you posted when package is supported.

**Comment by devops-github-rudderstack** [comment]
This issue is considered to be stale. It has been open for 30 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the issue.

**Comment by johnpkennedy** [comment]
Any update on this?

**Comment by devops-github-rudderstack** [comment]
This issue is considered to be stale. It has been open for 30 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the issue.
