### ISSUE TITLE
Update implementation of App Center source

### ISSUE THREAD

**Issue by ItsSudip** [rudderlabs/rudder-transformer#1724]
We are supporting app center as a source. Recently app center has updated its implementation of webhook initialization. When we are going to store one webhook url and testing that, app center is looking for a success response from the host of the webhook which is Rudderstack in our case. But as we are not returning any response from our side the tests from app center are always failing. 
![Screenshot 2022-12-22 at 9 35 53 AM](https://user-images.githubusercontent.com/67197965/209053396-892d79bf-ffdc-454f-98f9-85188c6f8688.png)

**Comment by anantjain45823** [comment]
Closing this issue as this change has been incorporated in #1741
