### ISSUE TITLE
FEATURE REQUEST: Forward Track events to Mailchimp Events API endpoint

### ISSUE THREAD

**Issue by fev4** [rudderlabs/rudder-transformer#1784]
**Is your feature request related to a problem? Please describe.**
Currently, Mailchimp only forwards Identify events. Given Mailchimp has an Events API, it can be beneficial for behavioral marketing to also forward Track events.

**Describe the solution you'd like**
Integrate Rudderstasck Track event in away that sends data to the Mailchimp Events API Add Event endpoint in order to trigger marketing campaigns via Automated Journeys (usecase).

Here're the doc: https://mailchimp.com/developer/marketing/api/list-member-events/add-event/

Notice this: the subscriber_hash is the MD5 hash of the lowercase version of the list member's email address. This endpoint also accepts a list member's email address or contact_id.

**Describe alternatives you've considered**
Using the API directly. But if we have Rudderstack in place, why wouldn't RS be a quicker/efficient solution?

**Additional context**
This would be incredible for automated journeys. https://mailchimp.com/help/use-events-behavioral-targeting/

**Comment by gitcommitshow** [comment]
Thank for creating the detailed feature request. Although this feature is not yet on the roadmap. 
We shall update this issue when it is prioritised.

**Comment by ItsSudip** [comment]
We have implemented this feature a few days ago. [Here](https://www.rudderstack.com/docs/destinations/streaming-destinations/mailchimp/#track) is the documentation regarding that. So I am closing this issue.
