### ISSUE TITLE
BUG: Klaviyo Double Opt-in failure

### ISSUE THREAD

**Issue by Alx-Li** [rudderlabs/rudder-transformer#1813]
**Describe the bug**
Adding a user to a list in Klaviyo with double-opt-in enabled via `identify()` would forcibly insert the user into the list. Even when the subscribe property is false.

if subscribe is false:
`identify() -> add to list`

if subscribe is true:
`identify() -> add to list -> send consent email.`

**To Reproduce**
1. follow [this guide](https://www.rudderstack.com/docs/user-guides/how-to-guides/rudderstack-jamstack-integration/rudderstack-nextjs-integration/#method-2-installing-and-configuring-the-javascript-sdk-using-npm-package-in-your-nextjs-app) to add Rudderstack to a Next.js app
2. connect a Klaviyo destination to the JS source, using a list that has double opt in enabled
3. Make an identify call in console or via a function tied to a button (I used 10 minute mail services to test the emails)

**Expected behavior**
After subscribing a user to a Klaviyo list with double opt-in enabled, the user should receive an email to confirm their subscription, then get added to the list.

`identify() -> consent email -> subscribe to list`

**Additional context**
This issue was discovered using the Javascript SDK npm package on Next.js.

**Comment by yashasvibajpai** [comment]
@Alx-Li The update for the issue reported here was released. Can you please verify and close the issue if fixed?

Thanks!

**Comment by Alx-Li** [comment]
Rudderstack no longer adds the user to a list if subscribe is set to false. However, now the issue is that if subscribe is set to true and the listID belongs to a list with double opt-in enabled, Klaviyo does not send the opt-in email to the user. 

if list has double opt-in enabled && subscribe is set to true:
`identify() -> <nothing> ` (note that Klaviyo receives the events and adds the profile, just not to a list)

expected behavior: 
`identify() -> user receives email confirmation -> added to list `

**Comment by ujjwal-ab** [comment]
> Rudderstack no longer adds the user to a list if subscribe is set to false. However, now the issue is that if subscribe is set to true and the listID belongs to a list with double opt-in enabled, Klaviyo does not send the opt-in email to the user.
> 
> if list has double opt-in enabled && subscribe is set to true: `identify() -> <nothing> ` (note that Klaviyo receives the events and adds the profile, just not to a list)
> 
> expected behavior: `identify() -> user receives email confirmation -> added to list `

We are working on the API version upgrade for Klaviyo. After that, it will be fixed.

**Comment by devops-github-rudderstack** [comment]
This issue is considered to be stale. It has been open for 30 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the issue.

**Comment by devops-github-rudderstack** [comment]
This issue is considered to be stale. It has been open for 30 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the issue.

**Comment by devops-github-rudderstack** [comment]
This issue is considered to be stale. It has been open for 30 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the issue.

**Comment by ujjwal-ab** [comment]
This issue is resolved.
