### ISSUE TITLE
Amplitude integration: platform attribute is not populated

### ISSUE THREAD

**Issue by twom** [rudderlabs/rudder-transformer#192]
![image](https://user-images.githubusercontent.com/277797/86806910-576a0b80-c047-11ea-86c3-78d2fbeaf69d.png)

As shown on the image, we are sending tracking events to Amplitude using Rudder react-native SDK and the Amplitude react-native sdk.

One of the differences we see is that Rudder is not populating the platform field (we see '-'), while amplitude tracking shows the platform (iOS). This is used prominently in Amplitude:  https://developers.amplitude.com/docs/http-api-v2

At this point, I am not familiar enough with the library to contribute directly, but would like to bring it up already!

**Comment by twom** [comment]
As an additional point: source type is React Native (mainly tested from iOS)

**Comment by arnab-p** [comment]
Thanks @twom for pointing this out. We'll look into it.

**Comment by sajalmohanta** [comment]
Hi @twom It has been fixed.
