### ISSUE TITLE
Bug: Possible incorrect handling of group events for the Mixpanel destination

### ISSUE THREAD

**Issue by staalezh** [rudderlabs/rudder-transformer#1941]
**Describe the bug**
It looks like there might be a bug in the Mixpanel destination. The [processGroupEvents](https://github.com/rudderlabs/rudder-transformer/blob/main/src/v0/destinations/mp/transform.js#L261) function seems to correctly construct Mixpanel events and set the Mixpanel endpoint to '${BASE_ENDPOINT}/groups/'. However, [responseBuilderSimple](https://github.com/rudderlabs/rudder-transformer/blob/main/src/v0/destinations/mp/transform.js#L65) does not seem have a switch-clause which handles group events (from what I can see, the endpoint ends up being overriden in the default-clause).

**Expected behavior**
`rudder_analytics.group(user_id=<user_id>', group_id='<group-id>', traits={'foo': 'Bar'})`

should create a group profile in Mixpanel.

**Actual behavior**
No group profile is created.

**Additional context**
I configured group keys in both RudderStack and Mixpanel as described in the documentation.

**Comment by Gauravudia** [comment]
@staalezh If you see the flow [responseBuilderSimple](https://github.com/rudderlabs/rudder-transformer/blob/main/src/v0/destinations/mp/transform.js#L65) is being called inside the [processGroupEvents](https://github.com/rudderlabs/rudder-transformer/blob/main/src/v0/destinations/mp/transform.js#L261) function and on line no. [298](https://github.com/rudderlabs/rudder-transformer/blob/821a3bb4e805f4f8896459d2c118af92b16e194f/src/v0/destinations/mp/transform.js#L298) Mixpanel groups endpoint is correctly configured and returned in the response. 
Furthermore, We are able to create the group profile successfully in Mixpanel.

[Sample group call](https://www.rudderstack.com/docs/event-spec/standard-events/group/)
`rudderanalytics.group("test777", {
  company_id: "456",
  name: "My Company",
  industry: "IT",
  employees: 450,
  plan: "basic"
})`
where `company_id` is the group key configured in Mixpanel and RudderStack dashboard. 
Note that the Group analytics feature is available on [Mixpanel](https://help.mixpanel.com/hc/en-us/articles/360025333632-Group-Analytics) Growth and Enterprise plan.

<img width="283" alt="Screenshot 2023-03-16 at 2 53 43 PM" src="https://user-images.githubusercontent.com/60897972/225572668-5ac6d698-5df3-4b53-a380-fc81b0933072.png">

**Comment by devops-github-rudderstack** [comment]
This issue is considered to be stale. It has been open for 30 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the issue.
