### ISSUE TITLE
Amplitude revenue tracking: revenueType missing in documentation (and probably need for snake case in transformer)

### ISSUE THREAD

**Issue by twom** [rudderlabs/rudder-transformer#198]
Amplitude documentation: https://help.amplitude.com/hc/en-us/articles/115003116888-Tracking-Revenue#h_7a841611-ad4f-459a-98ce-073a4a1fe8e5 includes revenueType

It is not here (https://docs.rudderstack.com/rudderstack-api-spec/rudderstack-ecommerce-events-specification/ordering or on the amplitude destination documentation

The transformer also has a camelCase version where it probably should be snake case (on the Rudder end): https://github.com/rudderlabs/rudder-transformer/blob/ca93487cd65455dc627022da194d2b87f373ea3c/v0/destinations/am/data/AmplitudeRevenueConfig.json#L16

https://github.com/rudderlabs/rudder-transformer/issues/197

**Comment by arnab-p** [comment]
https://github.com/rudderlabs/rudder-transformer/pull/209
