### ISSUE TITLE
Shynet support

### ISSUE THREAD

**Issue by jalberto** [rudderlabs/rudder-transformer#218]
Another nice Opensource tool to add support: https://github.com/milesmcc/shynet

**Comment by saikumarrs** [comment]
@jalberto Thanks for the suggestion. As we'll track this internally, closing the issue here.

**Comment by jalberto** [comment]
@saikumarrs does this means this is being worked on?  Or it has been discarded? I really do not understand, if you move the issue sot internal tracking (what ever that means) how is supposed the open community to be aware of it and participate?
