### ISSUE TITLE
BUG: Nested properties and arrays are not flattened for Intercom

### ISSUE THREAD

**Issue by tmchow** [rudderlabs/rudder-transformer#2471]
**Describe the bug**
Today, rudderstack does not flatten nested properties or arrays in either identify or track calls for Intercom.  This is a broken integration because it means you lose utility of user properties if you pass things in that are nested.

**To Reproduce**
Connect Intercom as a destination and do an identify call with nested user properties.   You'll see nested properties and arrays not supported.

**Expected behavior**
Event and user properties are flattened. 

**Screenshots**
n/a

**Additional context**

Intercom docs stating nested properties not supported: [Link](https://www.intercom.com/help/en/articles/5245634-event-limits-troubleshooting-and-f-a-q#:~:text=If%20you%20send%20events%20with%20nested%20metadata%2C%20containing%20multiple%20keys%20and%20values%20(like%20an%20object)%2C%20the%20metadata%20will%20be%20visible%20in%20the%20user%20list%2C%20but%20it%20will%20not%20be%20usable%20in%20messages.)

Intercom docs stating that objects AND arrays are not supported: [Link](https://www.intercom.com/help/en/articles/179-send-custom-user-attributes-to-intercom#:~:text=Data%20values%20must%20be%20sent%20as%20JSON%20strings%2C%20numbers%20or%20booleans%20(true%20or%20false).%20We%20can%E2%80%99t%20accept%20object%2C%20nested%20hashes%20and%20array%20data%20formats.)

**Comment by krishna2020** [comment]
@tmchow the fix has been released today - https://github.com/rudderlabs/rudder-transformer/releases/tag/1.38.0
You can test out the changes.
