### ISSUE TITLE
BUG: Nested properties not flattened for Klaviyo

### ISSUE THREAD

**Issue by tmchow** [rudderlabs/rudder-transformer#2472]
**Describe the bug**
Today, rudderstack does not flatten nested properties in either identify or track calls for Klaviyo.  This is a broken integration because it means you lose utility of properties if you pass things in that are nested.

Note: Unlike Intercom, Klaviyo supports arrays so only nested properties need to be flattened.

**To Reproduce**
Connect Klaviyo as a destination and do an identify call with nested user or event properties.  You'll see that user properties are not flattened and klaviyo stores the JSON objects as strings. These are not usable within Klaviyo as is.

**Expected behavior**
User properties are flattened.

**Screenshots**
n/a

**Additional context**
Today, rudderstack does not flatten nested properties or arrays in either identify or track calls for Klaviyo.  This is a broken integration because it means you lose utility of user properties if you pass things in that are nested.

**Klaviyo _does NOT_ support nested properties for identify** ([source](https://community.klaviyo.com/email-templates-and-coupons-32/multiple-variables-fallback-in-personalization-not-working-8871#:~:text=profile%20properties%20can't%20be%20nested
))
> I think there might be a few reasons why you weren’t having success calling your profile property previously. First, variables can only be nested if its an event variable, profile properties can’t be nested.

**Klaviyo _does_ support nested properties for events, but there are caveats for it that make them very difficult to use** ([source](https://community.klaviyo.com/campaigns-and-flows-30/trigger-splits-not-working-with-nested-properties-6508#:~:text=Nested%20data%20cannot%20be%20used%20in%20filters%20for%20flows%20or%20in%20segments%20)):
> Nested data cannot be used in filters for flows or in segments since the information is buried too deep in the event data. Only top-level properties can be searched for in flow filters and segment definitions. The only place where you can use nested data is in a flow email triggered by the event, where you can display any piece of info that lives in the event's dynamic data.

So this means that Rudderstack should:
1. Always flatten user properties/traits
2. Offer option to flatten event properties, and I recommend that default be on

My strong recommendation is that this should just always flatten user AND event properties.  Nested properties just don't work well even on events.

As it stands I've had to write my own custom transformation which is a nightmare to handle this and it should be handled like other destinations to flatten automatically

**Comment by tmchow** [comment]
@krishna2020 @shrouti1507 @ItsSudip @sandeepdsvs tagging you all in comments per the instructions on opening bugs

**Comment by ujjwal-ab** [comment]
Hi @tmchow, we tested by sending nested profile properties to Klaviyo and Klaviyo doesn't throw any error for that and the properties gets updated in the profile. Please let us know if you face any issue on this or we are missing anything here.

**Comment by tmchow** [comment]
> Hi @tmchow, we tested by sending nested profile properties to Klaviyo and Klaviyo doesn't throw any error for that and the properties gets updated in the profile. Please let us know if you face any issue on this or we are missing anything here.

They don't throw an error but as I mentioned in my ticket the properties aren't usable in a meaningful way. 

They even state that nested properties can't query any of the keys when trying to create deferments. It's just stored as string. 

This definitely must be fixed.

**Comment by krishna2020** [comment]
@tmchow For an array of objects in properties, 
1. Without flattening, it ends up in the same current position where all the fields will not be available for filtering
2. With flattening, to filter a particular field with some value - multiple filters might be required depending on the position of object in an array. Check the test case here - https://github.com/rudderlabs/rudder-transformer/pull/2491/files#diff-11856f84b258eae12c0575e05f13a754b1b4e98a6c741d18931117c6d19df6bdR1633 (To filter ItemPrice < 10, all filters with ItemPrice[n] need to be configured in Klaviyo)

We are going with option 2.

**Comment by tmchow** [comment]
> @tmchow For an array of objects in properties,
> 
> 1. Without flattening, it ends up in the same current position where all the fields will not be available for filtering
> 2. With flattening, to filter a particular field with some value - multiple filters might be required depending on the position of object in an array. Check the test case here - https://github.com/rudderlabs/rudder-transformer/pull/2491/files#diff-11856f84b258eae12c0575e05f13a754b1b4e98a6c741d18931117c6d19df6bdR1633 (To filter ItemPrice < 10, all filters with ItemPrice[n] need to be configured in Klaviyo)
> 
> We are going with option 2.

Amazing, thank you!

**Comment by ujjwal-ab** [comment]
Hey @tmchow , we released the flattening properties changes yesterday. 
- A new configuration setting is added in the UI ( to be backward compatible) which can be enabled to flatten the properties.
- By default flattening will not happen.

Thanks
