### ISSUE TITLE
BUG: rudderlabs/rudder-transformer:latest image is not up to date

### ISSUE THREAD

**Issue by othierry** [rudderlabs/rudder-transformer#3081]
**Describe the bug**

The `rudderlabs/rudder-transformer:latest` tag is not up-to-date with the code base ([version tag 1.55.0](https://github.com/rudderlabs/rudder-transformer/releases/tag/v1.55.0)).

[Link to dockerhub image](https://hub.docker.com/layers/rudderlabs/rudder-transformer/latest/images/sha256-dc83e666432e3eb9d76c8d1ae42e8b66f4233784e76168fe643c5a4bd9be183c?context=explore)

It still uses `v13` for googleapis which is now fuly deprecated and all requests are getting blocked (400 bad request)

```
{
  "response": "{\"status\":400,\"message\":\"[Google Ads Offline Conversions]:: [{\\\"error\\\":{\\\"code\\\":400,\\\"message\\\":\\\"Request contains an invalid argument.\\\",\\\"status\\\":\\\"INVALID_ARGUMENT\\\",\\\"details\\\":[{\\\"@type\\\":\\\"type.googleapis.com/google.ads.googleads.v13.errors.GoogleAdsFailure\\\",\\\"errors\\\":[{\\\"errorCode\\\":{\\\"requestError\\\":\\\"UNSUPPORTED_VERSION\\\"},\\\"message\\\":\\\"Version v13 is deprecated. Requests to this version will be blocked.\\\"}],\\\"requestId\\\":\\\"CyIivQWMr6KMB-fcL5EfJw\\\"}]}}] during google_ads_offline_conversions response transformation\",\"destinationResponse\":[{\"error\":{\"code\":400,\"message\":\"Request contains an invalid argument.\",\"status\":\"INVALID_ARGUMENT\",\"details\":[{\"@type\":\"type.googleapis.com/google.ads.googleads.v13.errors.GoogleAdsFailure\",\"errors\":[{\"errorCode\":{\"requestError\":\"UNSUPPORTED_VERSION\"},\"message\":\"Version v13 is deprecated. Requests to this version will be blocked.\"}],\"requestId\":\"CyIivQWMr6KMB-fcL5EfJw\"}]}}],\"statTags\":{\"errorCategory\":\"network\",\"errorType\":\"aborted\",\"destType\":\"GOOGLE_ADWORDS_OFFLINE_CONVERSIONS\",\"module\":\"destination\",\"implementation\":\"native\",\"feature\":\"dataDelivery\",\"destinationId\":\"[REDACTED]\",\"workspaceId\":\"[REDACTED]\"}}",
  "firstAttemptedAt": "2024-02-12T10:56:53.387Z",
  "content-type": "application/json"
}
```

**To Reproduce**
```
docker run --rm -it --entrypoint sh rudderlabs/rudder-transformer:latest
cat dist/src/v0/destinations/google_adwords_offline_conversions/config.js
```

**Expected behavior**

Expected to see `API_VERSION` to `v14` in `google_adwords_offline_conversions/config.js`

```
const API_VERSION = 'v14';
```

Currently is 

```
const API_VERSION = 'v13';
```

**Comment by sanpj2292** [comment]
Hi @othierry ,

Thank you for reporting this issue. Our team is looking into fixing this issue. Can you use the specific version(>= 1.53.0) to unblock yourselves ?

Please check and confirm if things are working well 🙂.

Thank you

**Comment by sanpj2292** [comment]
Also please refer the image from `rudderstack/rudder-transformer` instead of `rudderlabs/rudder-transformer`.

Once you check please let us know if all works well.

**Comment by gitcommitshow** [comment]
@othierry We've moved the docker organization from `rudderlabs` to `rudderstack`
Make sure your docker images for `rudder-transformer` are being pulled from `rudderstack/rudder-transformer`

**Comment by othierry** [comment]
Thank you very much for your answer. We will update we download images from the new orga.

**Comment by othierry** [comment]
@gitcommitshow I see `rudder-server` is still under `rudderlabs` organization. Do you also plan to also move it to `rudderstack` organization ? 

Thanks again.

**Comment by gitcommitshow** [comment]
No plans as of now. I will post in the slack community and github readme if any change is needed in rudder-server.
