### ISSUE TITLE
BUG: $identify is better with mixpanel than $merge

### ISSUE THREAD

**Issue by adityapatadia** [rudderlabs/rudder-transformer#3174]
**Describe the bug**
Using merge results in wrong location data. Ideally we should use $identify.

Here is the line that uses $merge:
https://github.com/rudderlabs/rudder-transformer/blob/db2c1703ec0daa34d44604acc06f592c3cf44521/src/v0/destinations/mp/transform.js#L281

Ideally this should use $identify and let mixpanel handle entire flow whether and how to merge the user. identify has better flow chart in terms of how to merge ID ans is recommended by Mixpanel:- https://developer.mixpanel.com/reference/create-identity

**To Reproduce**
When user is identified, the resulting user always has Ashburn USA as location.

**Expected behavior**
Location of user is taken as per IP address.

**Comment by gitcommitshow** [comment]
Hi Aditya, thank you for reporting the issue. Sorry, we missed this one.
Allow us a bit more time to look into this.

**Comment by adityapatadia** [comment]
No problem. Let me know if you need a PR—Regards,Aditya PatadiaOn 5 Apr 2024, at 11:54 PM, gitcommitshow ***@***.***> wrote:﻿
Hi Aditya, thank you for reporting the issue. Sorry, we missed this one.
Allow us a bit more time to look into this.

**Comment by gitcommitshow** [comment]
Received more info on this from the team. 

We already have a dropdown to choose the identify merge

1. **Original ID Merge**
2. **Simplified ID Merge** - if selected, RdderStack will not send the `$merge` call. You can select this option in webapp and enable the same option in mixpanel dashboard too.

Note:- Simplified ID merge will work on new projects only in mixpanel.

@adityapatadia Does this solve the problem or we would still require changes in the transform?

**Comment by adityapatadia** [comment]
This won't solve the problem as old projects can't use simplified ID merge in Mixpanel. If we switch to that mode, no merge or identify call will be ever sent and that would be problem for our old project. (Mixpanel says old projects can't use simplified merge. We need to create a new project).

The best course here is to switch to $identify call which will make sure everything works as it's supposed to.

**Comment by gitcommitshow** [comment]
Understood. In that case, the team will need time to evaluate this thoroughly making sure that the change does not affect other customers. Meanwhile, feel free to share more thoughts you have to help this move faster.

**Comment by adityapatadia** [comment]
Okay, as per doc it should not have any negative impact. As per the flow chart provided my mixpanel, identify only added a few more checks before it merges. The way it's done is much better where data of each profile is not overwritten. Happy to help you more but I hope this will be prioritised.

**Comment by Gauravudia** [comment]
@adityapatadia Merge does not support the IP in the payload. It is meant for merging unknown and known users only. When you make an identify call with both userId and anonymousId, RudderStack makes two calls:

- [/engage](https://developer.mixpanel.com/reference/profile-set) where IP is supported.
- [/import ](https://developer.mixpanel.com/reference/identity-merge)-> merge call.

You can refer to the documentation here: [Mixpanel Destination: Identify](https://www.rudderstack.com/docs/destinations/streaming-destinations/mixpanel/#identify).

I tested the flow in my Mixpanel account, and I could see the correct IP under `context.ip` reflected in the Mixpanel dashboard. 

Input payload to RudderStack
```
{
    "type": "identify",
    "traits": {
        "name": "John Doe",
        "plan": "basic",
        "email": "john.doe@example.com",
        "org_id": "orgId456",
        "company": {
            "id": "orgId456",
            "name": "Example Company",
            "website": "https://example.com"
        },
        "lastName": "Doe",
        "firstName": "John"
    },
    "userId": "7b9f4a801e9c59e2d3182f4c",
    "channel": "server",
    "context": {
        "ip": "xxx", // replaced with dummy value
        "traits": {
            "name": "John Doe",
            "plan": "basic",
            "email": "john.doe@example.com",
            "org_id": "orgId456",
            "company": {
                "id": "orgId456",
                "name": "Example Company",
                "website": "https://example.com"
            },
            "lastName": "Doe",
            "firstName": "John"
        }
    },
    "request_ip": "xxx",  // replaced with dummy value
    "anonymousId": "fb6de819-4305-4f7d-92e7-4e88dc64cbe3"
}
```

Transformed event to Mixpanel from live events:
```
[
    {
        "version": "1",
        "type": "REST",
        "method": "POST",
        "endpoint": "https://api.mixpanel.com/engage/",
        "headers": {},
        "params": {},
        "body": {
            "JSON": {},
            "JSON_ARRAY": {
                "batch": "[{\"$set\":{\"$email\":\"john.doe@example.com\",\"$name\":\"John Doe\",\"plan\":\"basic\",\"org_id\":\"orgId456\",\"company\":{\"id\":\"orgId456\",\"name\":\"Example Company\",\"website\":\"https://example.com\"},\"$firstName\":\"John\",\"$lastName\":\"Doe\"},\"$token\":\"xxx\",\"$distinct_id\":\"7b9f4a801e9c59e2d3182f4c\",\"$ip\":\"xxx\",\"$time\":1715058397772}]"
            },
            "XML": {},
            "FORM": {}
        },
        "files": {}
    },
    {
        "version": "1",
        "type": "REST",
        "method": "POST",
        "endpoint": "https://api.mixpanel.com/import/",
        "headers": {
            "Content-Type": "application/json",
            "Authorization": "Basic xxx"
        },
        "params": {
            "strict": 1
        },
        "body": {
            "JSON": {},
            "JSON_ARRAY": {},
            "XML": {},
            "FORM": {},
            "GZIP": {
                "payload": "[{\"event\":\"$merge\",\"properties\":{\"$distinct_ids\":[\"7b9f4a801e9c59e2d3182f4c\",\"fb6de819-4305-4f7d-92e7-4e88dc64cbe3\"],\"token\":\"xxx\"}}]"
            }
        },
        "files": {}
    }
]
```
Could you please check in live events what IP under `$ip` is sent to Mixpanel?

**Comment by adityapatadia** [comment]
It's not that, the problem is that when $merge is called, the merge happens wrong and the location taken is of merge caller and not from the real user.

Anyway, why this two step process is followed is a question. Everything will be simple if we use $identify. When we call identify in rudder, mixpanel should be sent $identify. We should change this behaviour.

**Comment by adityapatadia** [comment]
Why was this issue closed? Was this implemented?

**Comment by Gauravudia** [comment]
We can conduct further research on the impact of using $identify instead of /engage and $merge calls. However, I didn't understand this point:

> the merge happens wrong and the location taken is of merge caller and not from the real user

Mixpanel doesn't capture the IP for $merge calls and it don't affect the profile data.

**Comment by adityapatadia** [comment]
I don't know why but it always happens with our account. Let's do research on $identify and move to that. Segment (which we used previously) used $identify and everything worked fine.

**Comment by Gauravudia** [comment]
I have gone through this doc: [Create Identity](https://developer.mixpanel.com/reference/create-identity). Even if we use this, two calls are still required. The first one is with [/engage](https://developer.mixpanel.com/reference/profile-set) to create a user profile, and the second one is with create-identity, which will actually create the identity or merge the profiles. Additionally, IP is only supported in the /engage call. the create-identity call is just creating the identity and has nothing to do with the IP.

**Comment by Gauravudia** [comment]
@adityapatadia Could you please check from live events if the correct IP is being populated under the `$ip` property?

**Comment by adityapatadia** [comment]
How do I check what is being passed to Mixpanel? For most events it's going, only when we do identify, it shows as merge and location gets set as Virginia.

**Comment by adityapatadia** [comment]
My guess is that $merge call is merging the profiles in wrong way from mixpanel end. Identify call is merging things in right way on their end.

**Comment by Gauravudia** [comment]
You can check from RudderStack dashboard, From destination `Live events`
https://www.rudderstack.com/docs/dashboard-guides/live-events/#destination-live-events

**Comment by adityapatadia** [comment]
That is showing correct $ip.

**Comment by Gauravudia** [comment]
@adityapatadia Is the ip issue happening for all user profiles in mixpanel? 
Can you make sure to add the IP to `group` calls? The IP is missing under the "context" object for all group calls. Similarly, you need to add the IP for all other calls too, if you haven't already (track, page, and other calls).

**Comment by Gauravudia** [comment]
@adityapatadia We have added the support for `request_ip` (auto collected by RudderStack). Now, you should see the correct ip getting populated to mixpanel for `group` calls.
More info about this change :- https://www.rudderstack.com/docs/releases/mixpanel-ip-enhancement/

**Comment by adityapatadia** [comment]
Thanks for this but this has still not solved the problem. As I told you, may be if you can visit the merge and identity, it would be good.

**Comment by gitcommitshow** [comment]
@adityapatadia The IP issue is not related to merging. We reviewed the Mixpanel documentation but couldn't find any specific guidance on fixing IP issues using the API you suggested.
One suggestion is to pass the IP under `context.ip` for all events as mentioned [here](https://github.com/rudderlabs/rudder-transformer/issues/3174#issuecomment-2128524847)

Are we missing anything?

**Comment by adityapatadia** [comment]
I found the real cause of this issue. The problem is that IP needs to be passed as the `$ip` field in the `identify` call. Currently, `context.ip` was not passed to mixpanel as `$ip`. I just opened this PR to fix it: https://github.com/rudderlabs/rudder-transformer/pull/4202
