### ISSUE TITLE
BUG: AppsFlyer destination integration fails with 403 error: "redacted due to unsupported content-type"

### ISSUE THREAD

**Issue by petetnt** [rudderlabs/rudder-transformer#3790]
**Describe the bug**

I am trying to get the AppsFlyer cloud mode integration working.

Related SDK issue: https://github.com/rudderlabs/rudder-sdk-react-native/issues/381#issuecomment-2399449528

When debugging the SDK issue, I finally got the events to be forwarded to AppsFlyer. However the integration fails with the following error:

```
{
  "response": "redacted due to unsupported content-type",
  "firstAttemptedAt": "2024-10-08T10:21:00.166Z",
  "content-type": "application/octet-stream",
  "routerSubStage": "router_dest_delivery",
  "payloadStage": "router_input"
}
```

```
{
    "body": {
        "XML": {},
        "FORM": {},
        "JSON": {
            "ip": "89.27.52.57",
            "os": "17.4",
            "att": 0,
            "idfv": "139f7f31-d772-4ef3-9191-07fa496b640e",
            "eventName": "screen",
            "eventTime": "2024-10-08T10:20:49.709Z",
            "eventValue": "{\"name\":\"RewardCode\"}",
            "appsflyer_id": "1725356348180-1397317",
            "sharing_filter": "all",
            "app_version_name": "1.0.7",
            "bundleIdentifier": "com.REDACTED",
            "customer_user_id": "eede5cf6-49e8-4864-b214-c28545265cc4"
        },
        "JSON_ARRAY": {}
    },
    "type": "REST",
    "files": {},
    "method": "POST",
    "params": {},
    "userId": "",
    "headers": {
        "Content-Type": "application/json",
        "authentication": "REDACTED"
    },
    "version": "1",
    "endpoint": "https://api2.appsflyer.com/inappevent/id1667809195"
}
```

Not sure if the `AppsFlyer` is sending the error and RudderStack is failing to parse the response or if RudderStack is failing to send the event.

**To Reproduce**

1. Setup React Native project
2. Initalize the SDK

```ts
const rudderInitialise = async () => {
  const appsFlyerId = await appsFlyerNativeModule.getAppsFlyerId();

  await rudderClient.setup(
    Config.RUDDERSTACK_KEY,
    {
      logLevel: RUDDER_LOG_LEVEL.VERBOSE, //RUDDER_LOG_LEVEL[Config.RUDDER_LOG_LEVEL] ?? RUDDER_LOG_LEVEL.INFO,
      dataPlaneUrl: Config.RUDDERSTACK_DATA_PLANE_URL,
      trackAppLifecycleEvents: true,
      recordScreenViews: false,
    },
    {
      externalId: [
        {
          id: appsFlyerId,
          type: 'appsflyerExternalId'
        }
      ]
    }
  );
};

...
await rudderClient.identify(
  loggedInUser.id,
  {
    email: loggedInUser.email
  },
  {
    externalId: [
      {
        id: appsFlyerId,
        type: 'appsflyerExternalId'
      }
    ]
  }
);
```
4. Send a event:

```ts
rudderClient.screen('Foo', { bar: 'biz' })
```

**Expected behavior**

Event is sent to AppFlyer

**Screenshots**
<img width="1162" alt="image" src="https://github.com/user-attachments/assets/c5f04317-598d-48cb-afcd-7ae6cde142ad">

**Additional context**

**Comment by petetnt** [comment]
Hi @ItsSudip , @krishna2020 , @sandeepdsvs , @shrouti1507, would some of you have the time to check out this issue? It's currently blocking our go-live for the app and probably need to move away from RudderStack if there's no resolution for this particular issue.

**Comment by petetnt** [comment]
It seems that 403 comes from AppsFlyer if you are on Zero plan, which our test environment currently is.  See the docs: https://dev.appsflyer.com/hc/docs/testing-ios#i-get-response-403-on-install-or-event-recording

Should the error coming from AppsFlyer be parsed better anyway and shown on the Ruddestack UI? https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/477 had a similar issue which pointed me to right direction.

**Comment by petetnt** [comment]
Awesome, thanks @sanpj2292 !

**Comment by devops-github-rudderstack** [comment]
This issue is considered to be stale. It has been open for 30 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the issue.

**Comment by sanpj2292** [comment]
This is complete.
