### ISSUE TITLE
How to pass IDFV to Amplitude?

### ISSUE THREAD

**Issue by gilbertl** [rudderlabs/rudder-transformer#503]
The Amplitude HTTP API v2 has a property "IDFV" (https://developers.amplitude.com/docs/http-api-v2#properties-1) that can be used to integrate with other 3rd parties (e.g AppsFlyer). Looking at a sample payload, Rudderstack currently does not fill this property when calling Amplitude's API.

IDFV, AFAIK, is just the device_id on iOS devices. Rudderstack is already passing the device_id to Amplitude. It just hasn't been filling the IDFV field.

One way to fix this is have Rudderstack copy the device_id field over to the IDFV field for iOS events. 

Can we do that?

**Comment by arnab-p** [comment]
Fixed in https://github.com/rudderlabs/rudder-transformer/pull/518

**Comment by ryanmccrary** [comment]
@gilbertl wanted to make sure that you saw this was added. Let us know if you have any questions.

**Comment by ryanmccrary** [comment]
@gilbertl wanted to make sure that you saw this was added. Let us know if you have any questions.

**Comment by gilbertl** [comment]
Thanks. How should I upgrade Rudderstack to pick up this change?

**Comment by gilbertl** [comment]
> @gilbertl wanted to make sure that you saw this was added. Let us know if you have any questions.

I'm using Rudderstack open source. My understanding is that if I upgrade (using Helm Charts), I'd be upgrading rudder-server docker image tagged alpine-1. alpine-1 was last tagged 23 days ago. When can I expect your PR to be picked up there?

**Comment by ryanmccrary** [comment]
It's merged into master on this repo (rudder-transformer). The transformer version is specified here: https://github.com/rudderlabs/rudderstack-helm/blob/d9b6b9f17caac68ac10c1862b0b22647af7adab0/values.yaml#L91

**Comment by gilbertl** [comment]
> It's merged into master on this repo (rudder-transformer). The transformer version is specified here: https://github.com/rudderlabs/rudderstack-helm/blob/d9b6b9f17caac68ac10c1862b0b22647af7adab0/values.yaml#L91

Hi Ryan,

I notice that rudder-transformer hasn't updated it's "latest" release since Mar 2, 2020 (> 1 year ago!); when will the fix above make it into the release?

**Comment by gilbertl** [comment]
Hmm, it seems like the Github releases are not in sync with the docker image releases.

I see here that there are much newer releases
https://hub.docker.com/r/rudderlabs/rudder-transformer/tags?page=1&ordering=last_updated

and that I can specify the newer versions using Helm

Let me try that.

**Comment by gilbertl** [comment]
I upgraded my kubernetes deployment using the following command

```
helm upgrade our-rudderstack ./ --set rudderWorkspaceToken="redacted",backend.image.version="master",transformer.image.version="latest"
```

The upgrade seems to have gone smoothly. I checked my dataplaneUrl and it says everything is "UP."

I went to rudderstack dashboard to debug some live events going to Amplitude. However, the events still don't have "IDFV" properties."

Any idea why @arnab-p  ?

**Comment by gilbertl** [comment]
I think I see why. I have added a comment 

https://github.com/rudderlabs/rudder-transformer/pull/518/files#r642399527
