### ISSUE TITLE
utm_campaign incorrect tracking by JavaScript SDK and Mixpanel

### ISSUE THREAD

**Issue by vkovalskiy** [rudderlabs/rudder-transformer#714]
JavaScript SDK sends utm_campaign param as utm_name. The same way it goes into Mixpanel - utm_name. Which is incorrect. We are supposed to have utm_campaign there in both cases.
![image (2)](https://user-images.githubusercontent.com/564016/128767369-675f53b8-11a2-457b-abf8-b04a9cdbd4aa.png)

**Comment by vkovalskiy** [comment]
I have checked and found out that Rudder uses Segment UTM parser internally. This parser intentionally maps **utm_campaign** as **utm_name** in the request. Yet, Segment knows that info and with their backend, they transform it correctly into **utm_campaign** that is expected by the Mixpanel destination. Rudder does not do it and we have to make a manual transform until there will be a fix.

**Comment by sanpj2292** [comment]
@vkovalskiy

By both did you mean `campaign_id` and `utm_name` ? 
Is it something else ?

**Comment by vkovalskiy** [comment]
> @vkovalskiy
> 
> By both did you mean `campaign_id` and `utm_name` ?
> Is it something else ?

@sanpj2292 no, I was actually referring to the Rudderstack JS SDK Source  & Mixpanel Destination. But now I understand that your Source is compliant with Segment and the only thing required was the Mixpanel destination fix. Thanks!
