### ISSUE TITLE
Ruby <> PostHog url confusion

### ISSUE THREAD

**Issue by timgl** [rudderlabs/rudder-transformer#750]
We've had a user who users the ruby rudderstack library to send data to PostHog. They were sending data according to your docs, but PostHog requires the url to be `$current_url`, not `url`.

**Comment by arajguha** [comment]
@timgl  The value from `url` in the rudder payload is set as the value of `$current_url` in the destination payload by the rudder-transformer. Do you see any issues with the transformation?

**Comment by arajguha** [comment]
@timgl please set the `url` under `context.page.url`. Our transformation picks up the `context.page.url` and transforms it to `$current_url` in the destination payload.  Closing the issue with this comment.
