### ISSUE TITLE
AMP Analytics sends numbers as string

### ISSUE THREAD

**Issue by ameensom** [rudderlabs/rudder-transformer#790]
Hello

I'm using [amp-analytics ](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/configure-analytics/analytics-vendors/?format=websites#rudderstack) to send events to facebook.
What i've noticed is it's getting sent via query params in a url, something like this 
```
https://track.website.com/pixel/v1/track?writeKey=######&properties.quantity=20&properties.price=482
```
And what happens is the server reads the query params as strings and pass it on to the function on the line referenced below as string which then returns the error of 

```
TypeError: (revenue || 0).toFixed is not a function
```

https://github.com/rudderlabs/rudder-transformer/blob/bb50df3e30cca6f95163298577cbb647748ff525/v0/destinations/facebook_pixel/transform.js#L32

**Comment by saikumarrs** [comment]
Hi @ameensom!
Thanks for reporting this issue.
Could you please raise a PR with the following recommended fix? Also, feel free to suggest any other better alternatives.

`return Number((parseFloat(revenue) || 0).toFixed(2));
 `

**Comment by utsabc** [comment]
Hi @ameensom thank you for pointing out the issue,
Will you be willing to contribute to our project by creating a PR with the following recommended fix?
